#
# MUMPS
#

SET(MUMPS_INCLUDE_SEARCH_PATH
	${MUMPS_ROOT}/include
	/usr/include
	/usr/local/include/
)

SET(MUMPS_LIB_SEARCH_PATH
	${MUMPS_ROOT}/lib
	/usr/lib64
	/usr/lib
	/usr/local/lib/
)

FIND_PATH(MUMPS_INCLUDE_PATH       mumps_c_types.h      ${MUMPS_INCLUDE_SEARCH_PATH})

IF(H3D_REAL)
FIND_LIBRARY(MUMPSD_LIBRARY        dmumps               ${MUMPS_LIB_SEARCH_PATH})
ENDIF(H3D_REAL)
IF(H3D_COMPLEX)
FIND_LIBRARY(MUMPSZ_LIBRARY        zmumps               ${MUMPS_LIB_SEARCH_PATH})
ENDIF(H3D_COMPLEX)

FIND_LIBRARY(MUMPS_COMMON_LIBRARY  mumps_common         ${MUMPS_LIB_SEARCH_PATH})
FIND_LIBRARY(MUMPS_PORD_LIBRARY    pord                 ${MUMPS_LIB_SEARCH_PATH})
FIND_LIBRARY(MUMPS_MPISEQ_LIBRARY  mpiseq               ${MUMPS_LIB_SEARCH_PATH})

INCLUDE(FindPackageHandleStandardArgs)

IF(MUMPS_INCLUDE_PATH AND MUMPS_COMMON_LIBRARY AND MUMPS_PORD_LIBRARY AND MUMPS_MPISEQ_LIBRARY)
	SET(MUMPS_INCLUDE_DIR ${MUMPS_INCLUDE_DIR} ${MUMPS_INCLUDE_PATH})
	SET(MUMPS_LIBRARIES ${MUMPS_LIBRARIES} ${MUMPS_COMMON_LIBRARY})
	SET(MUMPS_LIBRARIES ${MUMPS_LIBRARIES} ${MUMPS_PORD_LIBRARY})
	SET(MUMPS_LIBRARIES ${MUMPS_LIBRARIES} ${MUMPS_MPISEQ_LIBRARY})
ENDIF(MUMPS_INCLUDE_PATH AND MUMPS_COMMON_LIBRARY AND MUMPS_PORD_LIBRARY AND MUMPS_MPISEQ_LIBRARY)

IF(H3D_REAL AND MUMPSD_LIBRARY)
	SET(MUMPS_LIB ${MUMPSD_LIBRARY})
	SET(MUMPS_LIBRARIES ${MUMPS_LIBRARIES} ${MUMPSD_LIBRARY})
	SET(MUMPS_FOUND TRUE)
ENDIF(H3D_REAL AND MUMPSD_LIBRARY)

IF(H3D_COMPLEX AND MUMPSZ_LIBRARY)
	SET(MUMPS_LIB ${MUMPS_LIB} ${MUMPSZ_LIBRARY})
	SET(MUMPS_LIBRARIES ${MUMPS_LIBRARIES} ${MUMPSZ_LIBRARY})
	SET(MUMPS_FOUND TRUE)
ENDIF(H3D_COMPLEX AND MUMPSZ_LIBRARY)

IF (MUMPS_FOUND)
	IF (NOT MUMPS_FIND_QUIETLY)
		MESSAGE(STATUS "Found MUMPS: ${MUMPS_LIB}")
	ENDIF (NOT MUMPS_FIND_QUIETLY)
ELSE (MUMPS_FOUND)
	IF (MUMPS_FIND_REQUIRED)
		MESSAGE(FATAL_ERROR "Could not find MUMPS")
	ENDIF (MUMPS_FIND_REQUIRED)
ENDIF (MUMPS_FOUND)
