#
# HDF5
#

#FIND_PATH(HDF5_INCLUDE_DIR hdf5.h /usr/include/ /usr/local/include/hdf5 ${HDF5_ROOT})
FIND_PATH(HDF5_INCLUDE_DIR hdf5.h ${HDF5_ROOT}/include)

#FIND_LIBRARY(HDF5_LIBRARY hdf5 /usr/lib/ /usr/local/lib/hdf5 ${HDF5_ROOT}) 
FIND_LIBRARY(HDF5_LIBRARY hdf5 ${HDF5_ROOT}/lib) 
#FIND_FILE(HDF5_LIBRARY libhdf5.a /usr/lib /usr/local/lib/hfd5 ${HDF5_ROOT}) 

IF (HDF5_INCLUDE_DIR AND HDF5_LIBRARY)
	SET(HDF5_FOUND TRUE)
ENDIF (HDF5_INCLUDE_DIR AND HDF5_LIBRARY)


IF (HDF5_FOUND)
	IF (NOT HDF5_FIND_QUIETLY)
		MESSAGE(STATUS "Found HDF5: ${HDF5_LIBRARY}")
	ENDIF (NOT HDF5_FIND_QUIETLY)
ELSE (HDF5_FOUND)
	IF (HDF5_FIND_REQUIRED)
		MESSAGE(FATAL_ERROR "Could not find HDF5")
	ENDIF (HDF5_FIND_REQUIRED)
ENDIF (HDF5_FOUND)

