PROJECT_NAME      = hermes1d
# input

FILE_PATTERNS     = *.cc *.h *.cpp *.py
EXCLUDE_PATTERNS  = */examples/*.cpp */examples/*.h */src/shapeset/*tetrad?.cc
SEARCHENGINE      = YES

RECURSIVE        = YES
GENERATE_LATEX   = NO
GENERATE_MAN     = NO
GENERATE_RTF     = NO
CASE_SENSE_NAMES = NO
GENERATE_HTML    = YES
GENERATE_XML     = YES
RECURSIVE        = YES

FULL_PATH_NAMES   = YES
STRIP_FROM_PATH   = ${PROJECT_SOURCE_DIR}
STRIP_FROM_INC_PATH = ${PROJECT_SOURCE_DIR}

EXAMPLE_PATH      = ${PROJECT_SOURCE_DIR}/examples
EXAMPLE_RECURSIVE = YES
EXAMPLE_PATTERNS  = *.cpp *.h

# output
OUTPUT_DIRECTORY     = ${PROJECT_BINARY_DIR}/doc/devel
JAVADOC_AUTOBRIEF    = YES
QT AUTOBRIEF         = YES
MULTILINE_CPP_IS_BRIEF = YES 
QUIET                = NO
WARNINGS             = NO
WARN_IF_DOC_ERROR    = NO
WARN_IF_UNDOCUMENTED = NO
WARN_NO_PARAMDOC     = NO

ALPHABETICAL_INDEX   = YES
