include ../../Make.config

NAME   = shapetest
#HERMES = ../../lib/libhermes2d-$(CC)-g-real.a
HERMES = ../../lib/libhermes2d-$(CC)-g-cplx.a
#FLAGS  = -ggdb 
FLAGS  = -ggdb -DH2D_COMPLEX

include ../Make.common
