#
# UFconfig
#

FIND_PATH(UFCONFIG_INCLUDE_DIR UFconfig.h ${UFCONFIG_ROOT} ${UFCONFIG_ROOT}/Include /usr/include/ /usr/local/include/UFconfig)

IF (UFCONFIG_INCLUDE_DIR)
   SET(UFCONFIG_FOUND TRUE)
ENDIF (UFCONFIG_INCLUDE_DIR)


IF (UFCONFIG_FOUND)
	IF (NOT UFCONFIG_FIND_QUIETLY)
#		MESSAGE(STATUS "Found UMFPACK: ${UMFPACK_LIBRARY}")
	ENDIF (NOT UFCONFIG_FIND_QUIETLY)
ELSE (UFCONFIG_FOUND)
	IF (UFCONFIG_FIND_REQUIRED)
		MESSAGE(FATAL_ERROR "Could not find UFconfig")
	ENDIF (UFCONFIG_FIND_REQUIRED)
ENDIF (UFCONFIG_FOUND)

