#
# Judy
#

FIND_PATH(JUDY_INCLUDE_DIR Judy.h ${JUDY_ROOT}/include)
FIND_LIBRARY(JUDY_LIBRARY Judy ${JUDY_ROOT}/lib) 

IF (JUDY_INCLUDE_DIR AND JUDY_LIBRARY)
	SET(JUDY_FOUND TRUE)
ENDIF (JUDY_INCLUDE_DIR AND JUDY_LIBRARY)


IF (JUDY_FOUND)
	IF (NOT JUDY_FIND_QUIETLY)
		MESSAGE(STATUS "Found Judy: ${JUDY_LIBRARY}")
	ENDIF (NOT JUDY_FIND_QUIETLY)
ELSE (JUDY_FOUND)
	IF (JUDY_FIND_REQUIRED)
		MESSAGE(FATAL_ERROR "Could not find Judy")
	ENDIF (JUDY_FIND_REQUIRED)
ENDIF (JUDY_FOUND)

