#
# Hermes3D
#


FIND_PATH(HERMES3D_INCLUDE_DIR hermes3d.h ${HERMES3D_ROOT}/include /usr/include/ /usr/local/include/hermes3d)
FIND_LIBRARY(HERMES3D_LIBRARY ${HERMES_BIN} ${HERMES3D_ROOT}/lib /usr/lib /usr/local/lib/hermes3d) 

IF (HERMES3D_INCLUDE_DIR AND HERMES3D_LIBRARY)
	SET(HERMES3D_FOUND TRUE)
ENDIF (HERMES3D_INCLUDE_DIR AND HERMES3D_LIBRARY)


IF (HERMES3D_FOUND)
	IF (NOT HERMES3D_FIND_QUIETLY)
		MESSAGE(STATUS "Found Hermes3D: ${HERMES3D_LIBRARY}")
	ENDIF (NOT HERMES3D_FIND_QUIETLY)
ELSE (HERMES3D_FOUND)
	IF (HERMES3D_FIND_REQUIRED)
		MESSAGE(FATAL_ERROR "Could not find Hermes3D")
	ENDIF (HERMES3D_FIND_REQUIRED)
ENDIF (HERMES3D_FOUND)

