#
# UMFPACK
#

#FIND_PATH(UFCONFIG_INCLUDE_DIR UFconfig.h /usr/include/ /usr/local/include/UFconfig ${UFCONFIG_ROOT}/Include)
FIND_PATH(UMFPACK_INCLUDE_DIR umfpack.h ${UMFPACK_ROOT}/Include /usr/include /usr/include/umfpack /usr/local/include/UMFPACK /usr/include/suitesparse)
FIND_PATH(AMD_INCLUDE_DIR amd.h ${AMD_ROOT}/Include /usr/include /usr/local/include/AMD /usr/include/suitesparse)

FIND_LIBRARY(UMFPACK_LIBRARY umfpack ${UMFPACK_ROOT}/Lib /usr/lib /usr/local/lib/UMFPACK) 
FIND_LIBRARY(AMD_LIBRARY amd ${AMD_ROOT}/Lib /usr/lib /usr/local/lib/AMD)

#IF (UFCONFIG_INCLUDE_DIR AND UMFPACK_INCLUDE_DIR AND AMD_INCLUDE_DIR AND UMFPACK_LIBRARY AND AMD_LIBRARY)
IF (UMFPACK_INCLUDE_DIR AND AMD_INCLUDE_DIR AND UMFPACK_LIBRARY AND AMD_LIBRARY)
   SET(UMFPACK_FOUND TRUE)
ENDIF (UMFPACK_INCLUDE_DIR AND AMD_INCLUDE_DIR AND UMFPACK_LIBRARY AND AMD_LIBRARY)


IF (UMFPACK_FOUND)
	IF (NOT UMFPACK_FIND_QUIETLY)
		MESSAGE(STATUS "Found UMFPACK: ${UMFPACK_LIBRARY}")
	ENDIF (NOT UMFPACK_FIND_QUIETLY)
ELSE (UMFPACK_FOUND)
	IF (UMFPACK_FIND_REQUIRED)
		MESSAGE(FATAL_ERROR "Could not find UMFPACK")
	ENDIF (UMFPACK_FIND_REQUIRED)
ENDIF (UMFPACK_FOUND)

