#
# Judy
#

FIND_PATH(JUDY_INCLUDE_DIR Judy.h ${JUDY_ROOT}/include)
FIND_LIBRARY(JUDY_LIBRARY Judy ${JUDY_ROOT}/lib)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(JUDY DEFAULT_MSG JUDY_INCLUDE_DIR JUDY_LIBRARY)
