#
# AMD
#

FIND_PATH(AMD_INCLUDE_DIR amd.h ${AMD_ROOT}/Include /usr/include /usr/local/include/AMD)
FIND_LIBRARY(AMD_LIBRARY amd ${AMD_ROOT}/Lib /usr/lib /usr/local/lib/AMD)

IF (AMD_INCLUDE_DIR AND AMD_LIBRARY)
   SET(AMD_FOUND TRUE)
ENDIF (AMD_INCLUDE_DIR AND AMD_LIBRARY)

IF (AMD_FOUND)
	IF (NOT AMD_FIND_QUIETLY)
		MESSAGE(STATUS "Found AMD: ${AMD_LIBRARY}")
	ENDIF (NOT AMD_FIND_QUIETLY)
ELSE (AMD_FOUND)
	IF (AMD_FIND_REQUIRED)
		MESSAGE(FATAL_ERROR "Could not find AMD")
	ENDIF (AMD_FIND_REQUIRED)
ENDIF (AMD_FOUND)

