#cmakedefine H2D_XML_SCHEMAS_DIRECTORY ${H2D_XML_SCHEMAS_DIRECTORY}
#cmakedefine H2D_PRECALCULATED_FORMS_DIRECTORY ${H2D_PRECALCULATED_FORMS_DIRECTORY}
#cmakedefine H2D_MAX_COMPONENTS ${H2D_MAX_COMPONENTS}
#cmakedefine H2D_MAX_QUADRATURES ${H2D_MAX_QUADRATURES}
#cmakedefine H2D_MAX_HANGING_NODES_LEVEL ${H2D_MAX_HANGING_NODES_LEVEL}
#cmakedefine H2D_USE_SECOND_DERIVATIVES ${H2D_USE_SECOND_DERIVATIVES}