#!/usr/bin/env bash
#
# Configures a particular version of Hermes.
#
# first argument : 
#   hermes_version/solver - Specifies a subdirectory under CMakeVars. 
#		    Interpreted as "Hermes version (Real only, Cplx only, 
#		    RealPlusCplx)"/"which solver(s) was Hermes configured 
#		    to run with"
# second argument: 
#   empty   sequential (or SMP) version; 
#   "mpi"   MPI version
#
# Examples:
#    ./run_configuration Real/all mpi

test -e CMake.vars && rm CMake.vars

if [ "$2" = "mpi" ] 
then
	conf_path="$1_$2"
else
	conf_path="$1"
fi

cp "CMakeVars/${conf_path}/CMake.vars" .

if [ "$2" = "mpi" ]
then
	./configure_for_openmpi
else
	test -e CMakeCache.txt && rm CMakeCache.txt
	cmake .
fi

cd src
make -j2

#cd ../tutorial
