#! /bin/sh

if [ "$SPKG_LOCAL" = "" ]; then
   echo "SPKG_LOCAL undefined ... exiting";
   exit 1
fi

set -e

# Set the hermes2d build options:
#python -c 'print "set(H2D_COMPLEX no)\nset(WITH_EXAMPLES no)\nset(WITH_TUTORIAL no)\nset(WITH_PYTHON yes)\nset(WITH_GLUT no)\nset(WITH_UTIL no)\nset(WITH_TESTS no)\nset(REPORT_WITH_LOGO no)\nset(WITH_BENCHMARKS no)"' > CMake.vars

cmake -DCMAKE_INSTALL_PREFIX="$SPKG_LOCAL" .

make
make install
