#! /bin/sh

set -e

if [ "$SPKG_LOCAL" = "" ]; then
   echo "SPKG_LOCAL undefined ... exiting";
   exit 1
fi

cp spkg-install ..
cd ..
# Forbid deletion of .git and other things for now, as it is unsafe if the user
# executes this by hand:
#rm -rf hermes1d hermes3d doc .git
