#
# GLEW
#

if(MSVC)
	set(GLEW_LIBRARY_NAME glew32)
else(MSVC)
	set(GLEW_LIBRARY_NAME GLEW)
endif(MSVC)

FIND_LIBRARY(GLEW_LIBRARY ${GLEW_LIBRARY_NAME} ${GLEW_ROOT}/lib /usr/lib64 /usr/lib /usr/local/lib64 /usr/local/lib)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(GLEW DEFAULT_MSG GLEW_LIBRARY)
