#
# Judy
#

FIND_PATH(JUDY_INCLUDE_DIR Judy.h
    PATHS $ENV{SPKG_LOCAL}/include ${JUDY_ROOT}/include
    NO_DEFAULT_PATH
    )
FIND_PATH(JUDY_INCLUDE_DIR Judy.h
    PATHS $ENV{SPKG_LOCAL}/include ${JUDY_ROOT}/include
    )
FIND_LIBRARY(JUDY_LIBRARY Judy
    PATHS $ENV{SPKG_LOCAL}/lib ${JUDY_ROOT}/lib
    NO_DEFAULT_PATH
    )
FIND_LIBRARY(JUDY_LIBRARY Judy
    PATHS $ENV{SPKG_LOCAL}/lib ${JUDY_ROOT}/lib
    )

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(JUDY DEFAULT_MSG JUDY_INCLUDE_DIR JUDY_LIBRARY)
