# !!! Keep the order of packages and libraries unless linking would be broken !!!
# !!! Do NOT edit the lines below UNLESS you are REALLY SURE what you are doing !!!
#

# Judy
set(TESTS_INCLUDE_DIRS ${TESTS_INCLUDE_DIRS} ${JUDY_INCLUDE_DIR})
set(TESTS_LIBRARIES ${TESTS_LIBRARIES} ${JUDY_LIBRARY}) 

# UMFPACK
if(WITH_UMFPACK)
	set(TESTS_INCLUDE_DIRS ${TESTS_INCLUDE_DIRS} 
		${UFCONFIG_INCLUDE_DIR}
		${UMFPACK_INCLUDE_DIR}
		${AMD_INCLUDE_DIR}
	)
	set(TESTS_LIBRARIES ${TESTS_LIBRARIES}
		${UMFPACK_LIBRARY}
		${AMD_LIBRARY}
	)

	set(TESTS_LIBRARIES ${TESTS_LIBRARIES} ${BLAS_LIBRARIES})
	set(TESTS_LIBRARIES ${TESTS_LIBRARIES} ${LAPACK_LIBRARIES})
endif(WITH_UMFPACK)

# PARDISO
if(WITH_PARDISO)
	set(TESTS_LIBRARIES ${TESTS_LIBRARIES} ${PARDISO_LIBRARY})
	set(TESTS_LIBRARIES ${TESTS_LIBRARIES} ${BLAS_LIBRARIES})
	set(TESTS_LIBRARIES ${TESTS_LIBRARIES} ${LAPACK_LIBRARIES})
endif(WITH_PARDISO)

# MUMPS
if(WITH_MUMPS)
	set(TESTS_INCLUDE_DIRS ${TESTS_INCLUDE_DIRS} ${MUMPS_INCLUDE_DIR})
	set(TESTS_LIBRARIES ${TESTS_LIBRARIES} ${MUMPS_LIBRARIES})
	set(TESTS_LIBRARIES ${TESTS_LIBRARIES} ${BLAS_LIBRARIES})
	set(TESTS_LIBRARIES ${TESTS_LIBRARIES} ${LAPACK_LIBRARIES})
	set(TESTS_LIBRARIES ${TESTS_LIBRARIES} ${CMAKE_THREAD_LIBS_INIT})
endif(WITH_MUMPS)

# PETSc
if(WITH_PETSC)
	set(TESTS_INCLUDE_DIRS ${TESTS_INCLUDE_DIRS} ${PETSC_INCLUDE_DIR})
	set(TESTS_LIBRARIES ${TESTS_LIBRARIES} ${PETSC_LIBRARIES})
	set(TESTS_LIBRARIES ${TESTS_LIBRARIES} ${PETSC_LIBS})

	set(TESTS_LIBRARIES ${TESTS_LIBRARIES} ${BLAS_LIBRARIES})
	set(TESTS_LIBRARIES ${TESTS_LIBRARIES} ${LAPACK_LIBRARIES})
endif(WITH_PETSC)

# Trilinos
if(WITH_TRILINOS)
	set(TESTS_INCLUDE_DIRS ${TESTS_INCLUDE_DIRS} ${TRILINOS_INCLUDE_DIR})
	set(TESTS_LIBRARIES ${TESTS_LIBRARIES} ${TRILINOS_LIBRARIES})
endif(WITH_TRILINOS)

# HDF5
if(WITH_HDF5)
	set(TESTS_INCLUDE_DIRS ${TESTS_INCLUDE_DIRS} ${HDF5_INCLUDE_DIR})
	set(TESTS_LIBRARIES ${TESTS_LIBRARIES} ${HDF5_LIBRARY})

#	# ZLIB
#	set(TESTS_LIBRARIES ${TESTS_LIBRARIES} ${ZLIB_LIBRARY})
endif(WITH_HDF5)

if(WITH_EXODUSII)
	set(TESTS_INCLUDE_DIRS ${TESTS_INCLUDE_DIRS} ${EXODUSII_INCLUDE_DIR})
	set(TESTS_LIBRARIES ${TESTS_LIBRARIES} ${EXODUSII_LIBRARIES})
endif(WITH_EXODUSII)

# METIS
if(WITH_METIS)
	set(TESTS_INCLUDE_DIRS ${TESTS_INCLUDE_DIRS} ${METIS_INCLUDE_DIR})
	set(TESTS_LIBRARIES ${TESTS_LIBRARIES} ${METIS_LIBRARY})
endif(WITH_METIS)


#if(USE_GLUT)
#	set(TESTS_INCLUDE_DIRS ${TESTS_INCLUDE_DIRS} ${GLUT_INCLUDE_DIR})
#	set(TESTS_LIBRARIES ${TESTS_LIBRARIES} ${GLUT_LIBRARY})
#endif(USE_GLUT)

